vdhicts/cyberfusion-cluster-api-client

CHANGELOG.md
README.md
composer.json
src/ClusterApi.php
src/Endpoints/Clusters.php
src/Endpoints/DatabaseUsers.php
src/Endpoints/MailAccounts.php
src/Endpoints/MailAliases.php
src/Endpoints/MailDomains.php
src/Endpoints/VirtualHosts.php
src/Models/DatabaseUser.php
src/Models/MailAccount.php
src/Models/MailAlias.php
src/Models/MailDomain.php
src/Models/VirtualHost.php

- Add database users endpoint.
- Add mail aliases endpoint.
- Add `balancer_backend_name` to virtualhosts.
- Add `catch_all_forward_email_addresses` to mail domain.
- Add commit call to the cluster endpoint. See the [readme](readme.md) for more information.
- Update to [API version 1.12](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.12-2021-02-23)
- Remove `forward_email_addresses` from mail accounts.

Update to version 1.12

---

CHANGELOG.md
README.md
src/Enums/ShellPath.php
src/Models/FpmPool.php
src/Models/UnixUser.php

- Add `is_namespaced` attribute to FPM pools.
- Add `shell_path` enum attribute to Unix Users.
- Update to [API version 1.32](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.32-2021-04-10)

Update to API version 1.32

---

CHANGELOG.md
src/Models/ClusterModel.php

- Add jsonSerializable support to the models. This allows you to `json_encode` the models.

Add jsonSerializable support to the models

---

CHANGELOG.md
README.md
src/Enums/ShellPath.php
src/Models/Cluster.php

- Add `command_toolkit_enabled` attribute to Clusters.
- Update to [API version 1.34](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.34-2021-04-23)
- The `nologin` shell path is no longer available.

Update to API version 1.34

---

CHANGELOG.md
README.md
src/ClusterApi.php
src/Endpoints/BorgArchives.php
src/Endpoints/BorgRepositories.php
src/Endpoints/SshKeys.php
src/Enums/ClusterGroup.php
src/Models/BorgArchive.php
src/Models/BorgRepository.php
src/Models/BorgRepositoryUsage.php
src/Models/Cluster.php
src/Models/Cms.php
src/Models/Malware.php
src/Models/SshKey.php

- Borg repository usages and update endpoint.
- Borg archives get endpoint.
- Add the `BORG_SERVER` cluster group.
- Add `private_key` property to SSH keys.
- Add malware toolkit fields to Cluster.
- Add `unix_user_id` property to Malware.
- Renamed `BORG` cluster group to `BORG_CLIENT` to match the spec.
- Retention fields of a borg repository are now nullable.
- Renamed `name` attribute of a CMS to `software_name` to match the spec.
- Removed the `virtual_host_id` property from malware.

Update to API version 1.45

---

src/Endpoints/VirtualHosts.php
src/Models/VirtualHost.php

- Add `get_document_root_contains_files` parameter to the `get` method on VirtualHost.

Update to API version 1.46

---

CHANGELOG.md
src/Client.php
src/Models/VirtualHost.php

- Fix error with deployment due to affected clusters not being initialized.
- Fix error with the document root files being `null` when no files are present but an array is expected.

Fix issue with deployment and virtualhost

---

CHANGELOG.md
src/Models/Cluster.php

Added a default empty string to the `setName` on a Cluster-model in the `fromArray` method, as the response of a cluster-commit does not contain a `name` property.

Add default empty string to setName in fromArray on the Cluster model

---

CHANGELOG.md
README.md
src/Endpoints/Crons.php
src/Models/Cron.php
src/Models/DatabaseUser.php
src/Models/DatabaseUserGrant.php

- Add regex validation to the name of a database user.
- Add `locking_enabled` property to crons.
- Change regex validation to allow capticals for the `table_name` of a database user grant.
- Update to [API version 1.47](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.47-2021-06-04)

Update to API version 1.47

---

CHANGELOG.md
README.md
src/Endpoints/Certificates.php
src/Models/Certificate.php
src/Models/ClusterModel.php
src/Support/Str.php

- Requesting a Let's Encrypt certificate not longer requires a cluster deployment.
- Update to [API version 1.48](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.48-2021-06-17)

Update to API version 1.48

---

src/Endpoints/Databases.php

Changed the databases usages endpoint which now correctly sets response data as a array. Made it exacly the same as the Unix Users usages request.

update database usage api endpoint

---

CHANGELOG.md
src/Client.php
src/Endpoints/BorgRepositories.php
src/Endpoints/Databases.php
src/Endpoints/MailAccounts.php
src/Endpoints/UnixUsers.php

Properly encode timestamps in usage endpoints

---

src/Models/FpmPool.php

Please consider using @phpstan.
It is superior to Psalm.

Fix unit name's type in FpmPool

---

CHANGELOG.md
src/Client.php

- Fix the type of the unix name in the FPMPool model. Thanks to @szepeviktor.

Prepare release for 1.30.1

---

CHANGELOG.md
src/Client.php
src/Support/ListFilter.php
tests/Support/LogFilterTest.php

- Use reflection instead of toArray to determine the available fields to prevent accessing fields which aren't 
initialized.

Fix list filter for a model

---

CHANGELOG.md
README.md
src/Client.php
src/Exceptions/ClusterApiException.php
src/Exceptions/ModelException.php
src/Models/DatabaseUser.php

- Update to [API version 1.97](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.97-2021-12-02).
- Always send the hashed password for the Database User but be able to set the hashed password with `setHashedPassword`
or plain text password with `setPassword`. Thanks to @mbardelmeijer.
- Setting the Database Engine of the Database User after setting the password will result in a `ModelException` as the
password hash is based on the engine.

Update to API version 1.97

---

CHANGELOG.md
src/Client.php
src/Models/DatabaseUser.php

I tested the implementation from https://github.com/vdhicts/cyberfusion-cluster-api-client/pull/77, which requires a small fix, which is provided by this PR.
The inner SHA-1 hash should be a binary digest with a length of 20 chars. The outer SHA-1 hash should be hexadecimal number with a length of 40 chars.

Use digest for the inner SHA-1 hash

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
CHANGELOG.md
README.md
src/Client.php
src/Endpoints/Certificates.php
src/Endpoints/SshKeys.php

As API version 1.101 has some breaking changes for the SSL certificates, I already prepared the code for the new version. Will merge as soon as the changes to the API are released.
- Add the Let's Encrypt certificate endpoint: `createLetsEncryptCertificate`.
- Add the endpoint to provide your own SSL certificates: `createCertificateWithOwnMaterial`.
- Update to [API version 1.101](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.101-2021-12-14).
- Issue templates to assign the correct user instead of the organisation. Also made the bug report a bit easier to use.
- Not all headers in this changelog were of the correct depth.
- Remove the `common_names` and `main_common_name` from the certificate update as it can't be changed.
- Remove the SSH key update endpoint as it's no …

Prepare update to API version 1.101

---

CHANGELOG.md
README.md
src/Client.php
src/Models/Certificate.php

- Add the `is_lets_encrypt` property to the `Certificate` model.
- Update to [API version 1.102](https://test-cluster-api.cyberfusion.nl/redoc#section/Changelog/1.102-2021-12-15).

Update to API version 1.102

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/DatabaseUserGrants.php
src/Support/ListFilter.php

- Update to [API version 1.103](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.103-2021-12-16).
- Use the proper snake_case fields when using the ListFilter.
- Remove the database user grant delete endpoint as it's no longer available.

Update to API version 1.103

---

CHANGELOG.md
README.md
src/Client.php
src/ClusterApi.php
src/Endpoints/UrlRedirects.php
src/Enums/ClusterGroup.php
src/Enums/StatusCode.php
src/Models/ClusterModel.php
src/Models/UrlRedirect.php

- Add URL redirects endpoint, example:
```php
$urlRedirect = (new UrlRedirect())
->setDomain('domlimev.nl')
->setDestinationUrl('https://www.cyberfusion.nl')
->setBalancerBackendName('YOUR-BALANCER-BACKEND')
->setClusterId(YOUR_CLUSTER_ID);
```
- Update to [API version 1.104.1](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.104.1-2021-12-20).

Update to API version 1.104.1

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/Certificates.php
src/Models/UrlRedirect.php

- Add `description` to the `UrlRedirect` model.
- Update to [API version 1.105.0](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.105-2021-12-28).
- Remove the `update` method from the `Certificate` endpoint.

Update to API version 1.105

---

CHANGELOG.md
src/Client.php
src/Enums/StatusCode.php

This ensures the `StatusCode` enum matches the `StatusCodeEnum` from the Cluster API.

Replace status code multiple choice (300) by see other (303)

---

CHANGELOG.md
src/Client.php
src/Endpoints/VirtualHosts.php

- Make sure the `allow_override_directives` and `allow_override_option_directives` are in the request body of the 
`VirtualHost`. 
Closes #86

Fix allow_overrides_* fields for the virtualhost

---

CHANGELOG.md
README.md
composer.json
src/Client.php
src/Endpoints/FpmPools.php
src/Endpoints/SshKeys.php
src/Enums/Host.php
src/Enums/Limit.php
src/Enums/Sort.php
src/Models/BorgArchive.php
src/Models/BorgRepository.php
src/Models/Certificate.php
src/Models/ClusterModel.php
src/Models/CmsInstallation.php
src/Models/Cron.php
src/Models/DatabaseUser.php
src/Models/FpmPool.php
src/Models/MailAccount.php
src/Models/MailAlias.php
src/Models/MailDomain.php
src/Models/SshKey.php
src/Models/UnixUser.php
src/Models/UrlRedirect.php
src/Models/VirtualHost.php
src/Support/ListFilter.php
src/Support/LogFilter.php
tests/Support/LogFilterTest.php

Closes #88 
- Add `log_slow_requests_threshold` attribute to the `FpmPool` model.
- Add `createPublic` and `createPrivate` methods to the `SshKeys` endpoint for creating a public or private SSH key.
- Add several validations for several attributes.
- Add `sort` attribute to the `LogFilter`.
- Update to [API version 1.106](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.106-2022-01-21).
- Moved the sort and limit constants to their own enums.

Update to API version 1.106

---

CHANGELOG.md
README.md
src/Client.php
src/Models/MailAccount.php
src/Models/MailAlias.php

Update mail accounts and mail aliases local part regex to allow dots and hyphens.

Update to API version 1.106.2

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/FpmPools.php

Add the ability to reload an FPM pool (added in Cluster API version 1.107).
This release ups the supported Cluster API version from 1.106.2 to 1.107. @dvdheiden, please double-check that no changes have to be made to this library for Cluster API versions 1.106.3, 1.106.4 and 1.106.5.

Version 1.41.0

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/Crons.php
src/Models/Cron.php

Add `node_id` attribute to the `Cron` model.

Version 1.42.0

---

.github/workflows/ci.yml
README.md

Add tests for the supported PHP versions.

Add PHP 8.1 tests

---

CHANGELOG.md
README.md
src/Client.php
src/ClusterApi.php
src/Endpoints/Cmses.php
src/Endpoints/FpmPools.php
src/Endpoints/TaskCollections.php
src/Enums/TaskCollectionType.php
src/Models/TaskCollection.php
src/Support/Arr.php
src/Support/Str.php

- Add `TaskCollection` endpoint.
- Add `callbackUrl` to cms install and fpm reload requests.
- Update to API version 1.110.
- The cms install and fpm reload request now return a `TaskCollection`.

Update to API version 1.110

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/BorgRepositories.php
src/Endpoints/Databases.php
src/Endpoints/MailAccounts.php
src/Endpoints/TaskCollections.php
src/Endpoints/UnixUsers.php
src/Enums/TimeUnit.php

- Add the optional `timeUnit` to database, mail account, borg repository and unix user usage.
- Update to [API version 1.115](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.115-2022-03-04).
- Renamed `from_timestamp_date` parameter to `timestamp`. This does not affect the usage of the package.

Update to API version 1.115

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/FpmPools.php
src/Endpoints/UnixUsers.php
src/Endpoints/UrlRedirects.php
src/Models/UnixUser.php

This PR adds the new attribute `record_usage_files` to UNIX users. It also adds missing attributes from create and update payloads for FPM pools, UNIX users and URL redirects.
Please ensure that tests are run, as they don't seem to be triggered for my fork.

Version 1.47.0

---

.github/workflows/ci.yml

When forks are merged into this package, this CI weren't triggered. This PR takes care of that.

Run tests on pull requests too

---

CHANGELOG.md
src/Client.php
src/Models/Cron.php

- Changed the `nodeId` property of the `Cron` model to optional.

Fix nodeId to be optional for the cron

---

CHANGELOG.md
README.md
composer.json
tests/Support/ValidatorTest.php

- Laravel 9 support failed due to using an old version of ramsey/uuid package to still support PHP 7.4. I intend to 
support PHP 7.4 until its EOL date (28 Nov 2022) when possible.

Fix Laravel 9 support

---

CHANGELOG.md
src/Endpoints/TaskCollections.php

- After talking to @WilliamDEdwards the task collection works a bit different then I thought. In short: a task 
collection contains at least 2 task and always returns the results of all those tasks. Updated the endpoint to reflect
that setup. The official documentation will be improved to provide more information about task collections and the 
results.

Expect multiple task results from the task collection results

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/BorgArchives.php
src/Enums/PassengerAppType.php
src/Enums/PassengerEnvironment.php

This PR updates the library to support Cluster API version 1.119.

Version 1.50.0

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/BorgArchives.php

- Add new path query parameter to download
- Add new path query parameter to restore
- Add missing path query parameter to contents

Version 1.51.0

---

CHANGELOG.md
README.md
src/Client.php
src/Models/PassengerApp.php
src/Support/Validator.php
tests/Support/ValidatorTest.php

- Change validation of `startup_file` of `PassengerApp` to end with `.js`
- Update to [API version 1.124.1](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.124.1-2022-05-21).
Closes #120

Update to API version 1.124.1

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/Clusters.php

Version 1.55.0

---

CHANGELOG.md
README.md
src/Client.php
src/Enums/DatabaseUserGrantPrivilegeName.php
src/Models/DatabaseUserGrant.php

Add new `DatabaseUserGrantPrivilegeName` enum with new `SELECT` database user grant privilege name.
`DEFAULT_PRIVILEGE_NAME` has been removed in favour of the enum, but the default value for `privilegeName` remains the same.

Version 1.57.0

---

CHANGELOG.md
src/Endpoints/BorgArchives.php
src/Endpoints/BorgRepositories.php
src/Endpoints/Clusters.php
src/Endpoints/PassengerApps.php

Just a tiny cleanup that doesn't require a separate release, so no version bump here as this should be released with the following change.
- Update docblocks.
- Remove unused imports.
- Remove `sprintf` calls without parameters.

Small cleanup

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/Databases.php
src/Models/DatabaseComparison.php

Closes #126 
- Add database comparison endpoint.
- Update docblocks.
- Remove unused imports.
- Remove `sprintf` calls without parameters.

Update to API version 1.128.1

---

CHANGELOG.md
README.md
src/Client.php
src/Models/VirtualHost.php

Add the `domainRoot` attribute to virtual host.

Version 1.59.0

---

CHANGELOG.md
README.md
src/Client.php
src/Models/TaskCollection.php

Add the `objectId` and `objectModelName` attributes to task collection.

Version 1.61.0

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/BorgArchives.php
src/Endpoints/BorgRepositories.php
src/Models/BorgArchiveMetadata.php

- Add Borg repository archives metadata endpoint.
- Borg archive metadata now has its own model, `BorgArchiveMetadata`.

Version 1.63.0

---

CHANGELOG.md
README.md
src/Client.php
src/ClusterApi.php
src/Endpoints/BasicAuthenticationRealms.php
src/Endpoints/Cmses.php
src/Endpoints/HtpasswdFiles.php
src/Endpoints/HtpasswdUsers.php
src/Enums/CmsConfigurationConstantName.php
src/Enums/CmsOptionName.php
src/Models/BasicAuthenticationRealm.php
src/Models/CmsConfigurationConstant.php
src/Models/CmsOption.php
src/Models/CmsOptionName.php
src/Models/HtpasswdFile.php
src/Models/HtpasswdUser.php

Add CMS options endpoint.
The `name` path parameter is an Enum. Other endpoints that need an Enum do not use the `valueIn` validation that models use for Enums. I don't know if there is a reason for that. If there is, commit https://github.com/vdhicts/cyberfusion-cluster-api-client/commit/7e1476ca8a816dca450cb39cb9ebecba5b51909d can be easily dropped.

Version 1.65.0

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/Cmses.php

Add CMS regenerate salts endpoint.

Version 1.67.0

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/RedisInstances.php
src/Models/RedisInstance.php

Add the `primaryNodeId` attribute to Redis instances.

Version 1.69.0

---

CHANGELOG.md
src/Client.php
src/Endpoints/VirtualHosts.php

- Add the required `domainRoot` attribute to the virtual host update payload.
The `domainRoot` attribute was added to the validation layer on https://github.com/vdhicts/cyberfusion-cluster-api-client/pull/139, but missed in the `update` call's payload.

Version 1.69.1
