vdhicts/cyberfusion-cluster-api-client

CHANGELOG.md
src/Client.php
src/Exceptions/ClientException.php
src/Exceptions/ClusterApiException.php
src/Models/Health.php

Add API availability check

---

src/Client.php
src/Endpoints/Authentication.php
src/Request.php

The authentication request require the data to be `application/x-www-form-urlencoded` but the other requests require `application/json`.

Update the request to use the proper schema

---

CHANGELOG.md
src/Client.php
src/Endpoints/UnixUsers.php

- Add directory fields to the unix user.
- Properly handle HTTP 500 errors.

Add directory fields for the unix users

---

CHANGELOG.md
src/Endpoints/Endpoint.php
src/Endpoints/FpmPools.php

- Fix general validation check to not mark a boolean with `false` or an empty array as invalid.
- Fix validation field for FPM pool endpoint

Fix validation

---

CHANGELOG.md
src/ClusterApi.php
src/Endpoints/Commands.php
src/Models/Command.php

- Add commands endpoint which were added in [API version 1.16](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.16-2021-03-05).
- - Update to [API version 1.17](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.17-2021-03-08)

Update to cluster API version 1.17

---

CHANGELOG.md
README.md
src/Endpoints/Databases.php
src/Endpoints/Endpoint.php
src/Endpoints/MailAccounts.php
src/Endpoints/MailDomains.php
src/Endpoints/UnixUsers.php
src/Models/MailDomain.php

- Add `from` parameter to unix user, database and mail accounts usages.
- Add mail domains update method.
- Add mail domains `is_local` property.
- Update to [API version 1.19](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.19-2021-03-12)

Update to cluster API version 1.19

---

CHANGELOG.md
src/Endpoints/Clusters.php
src/Models/Cluster.php

- Fix issue with cluster deployments (#19)

Fix issue with invalid cluster deployment configuration

---

CHANGELOG.md
src/Endpoints/Malwares.php
src/Models/DatabaseUser.php

- Add `host` attribute to database users.
- Add endpoint for retrieving the malware of a virtual host.

Update to API version 1.21

---

CHANGELOG.md
src/ClusterApi.php
src/Endpoints/DatabaseUserGrants.php
src/Endpoints/DatabaseUsers.php
src/Models/Database.php
src/Models/DatabaseUser.php
src/Models/DatabaseUserGrant.php

- Add crud for databases.
- Add crud for database users.
- Add crud for database user grants.
- Update to [API version 1.22](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.22-2021-03-23)

Update to API version 1.22

---

CHANGELOG.md
src/Endpoints/Cmses.php
src/Models/Cms.php

- Add support for one time login url for cmses.

Add support for one time login url for cmses

---

CHANGELOG.md
README.md
src/Enums/AllowOverrideDirectives.php
src/Enums/AllowOverrideOptionDirectives.php
src/Enums/DatabaseEngine.php
src/Models/ClusterModel.php
src/Models/Database.php
src/Models/DatabaseUser.php
src/Models/VirtualHost.php

- Update to [API version 1.29.1](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.29.1-2021-04-07)

Update to Cluster API version 1.29.1

---

.github/PULL_REQUEST_TEMPLATE.md

Add the check for the cluster API version in the readme.md to the PR template.

Add cluster API version check

---

CHANGELOG.md
src/Support/Str.php

- Fix pattern validation on models.

Fix pattern validation on models

---

CHANGELOG.md
src/Endpoints/DatabaseUserGrants.php
src/Endpoints/FpmPools.php
src/Endpoints/MailDomains.php
src/Endpoints/UnixUsers.php

- Change the required fields to match the latest spec.

Update required fields

---

CHANGELOG.md
README.md
src/ClusterApi.php
src/Endpoints/BorgRepositories.php
src/Enums/ClusterGroup.php
src/Models/BorgRepository.php

- Add Borg Repositories endpoint.
- Update to [API version 1.35.1](https://cluster-api.cyberfusion.nl/redoc#section/Changelog/1.35.1-2021-04-28)

Update to API version 1.35.1

---

CHANGELOG.md
src/Models/ClusterModel.php
src/Models/DatabaseUserGrant.php

- Fix empty string for all tables on database grants.

Fix null value for all tables on database grants

---

CHANGELOG.md
src/Endpoints/VirtualHosts.php
src/Models/VirtualHost.php

Update changelog for 1.46

---

CHANGELOG.md
README.md
src/Client.php
src/Configuration.php
src/Contracts/Client.php
src/Endpoints/BorgArchives.php
src/Endpoints/BorgRepositories.php
src/Endpoints/Certificates.php
src/Endpoints/Clusters.php
src/Endpoints/Cmses.php
src/Endpoints/Commands.php
src/Endpoints/Crons.php
src/Endpoints/DatabaseUserGrants.php
src/Endpoints/DatabaseUsers.php
src/Endpoints/Databases.php
src/Endpoints/Endpoint.php
src/Endpoints/FpmPools.php
src/Endpoints/Health.php
src/Endpoints/Logs.php
src/Endpoints/MailAccounts.php
src/Endpoints/MailAliases.php
src/Endpoints/MailDomains.php
src/Endpoints/Malwares.php
src/Endpoints/SshKeys.php
src/Endpoints/UnixUsers.php
src/Endpoints/VirtualHosts.php
src/Models/ClusterModel.php
src/Models/DatabaseUserGrant.php
src/Support/Arr.php
src/Support/Deployment.php

- Add (auto) deployment of affected clusters. See the [README.md](README.md) for more information about the usage of 
deployments.

Add deployment feature

---

CHANGELOG.md
README.md
src/Endpoints/Cmses.php
src/Endpoints/VirtualHosts.php
src/Models/Cms.php
src/Models/VirtualHost.php

Update to API version 1.88

---

src/Models/ClusterModel.php

Fix a type in PHPDoc.
Discovered by @phpstan

Fix type in ClusterModel

---

README.md

Improve required PHP version in the readme.

Improve required PHP version in the readme

---

CHANGELOG.md
src/Client.php
src/Models/Cron.php
src/Models/FpmPool.php

Fix issue with properties which aren't required. Closes #75

Fix issue with properties which aren't required

---

CHANGELOG.md
src/Client.php
src/Models/BorgArchive.php
src/Models/BorgRepository.php
src/Models/Certificate.php
src/Models/ClusterModel.php
src/Models/CmsInstallation.php
src/Models/Cron.php
src/Models/Database.php
src/Models/DatabaseUser.php
src/Models/DatabaseUserGrant.php
src/Models/FpmPool.php
src/Models/MailAccount.php
src/Models/MailAlias.php
src/Models/MailDomain.php
src/Models/SshKey.php
src/Models/UnixUser.php
src/Models/UrlRedirect.php
src/Models/VirtualHost.php
src/Support/Validator.php
tests/Support/ValidatorTest.php

- Full rework of the validation logic in the models including tests.

Rework validation logic

---

.github/PULL_REQUEST_TEMPLATE.md

Fix typo (support -> supported) in pull request template

---

CHANGELOG.md
README.md
src/Client.php
src/ClusterApi.php
src/Endpoints/Crons.php
src/Endpoints/Nodes.php
src/Enums/NodeGroup.php
src/Models/Cron.php
src/Models/Node.php

- Add nodes
- Add `random_delay_max_seconds` to crons

Version 1.43.0

---

CHANGELOG.md
src/Client.php
src/Models/UnixUser.php

Fixes https://github.com/vdhicts/cyberfusion-cluster-api-client/pull/102
Please ensure that tests are run, as they don't seem to be triggered for my fork.

Version 1.47.1

---

CHANGELOG.md
composer.json
src/Endpoints/TaskCollections.php
src/Enums/TaskState.php
src/Models/TaskResult.php
src/Support/Validator.php

- Properly implement the task collection results.

Properly implement task results

---

CHANGELOG.md
README.md
src/Client.php
src/ClusterApi.php
src/Endpoints/RootSshKeys.php
src/Models/RootSshKey.php

Version 1.52.0

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/UnixUsers.php
src/Models/Cluster.php
src/Models/UnixUserComparison.php

Update to API version 1.130.1.

Version 1.60.0

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/Databases.php
src/Endpoints/FpmPools.php
src/Endpoints/PassengerApps.php

- Add database sync endpoint
- Update Passenger app restart + FPM pool restart endpoints: add callback URL + return task collection model

Version 1.62.0

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/VirtualHosts.php

Add virtual host sync domain root endpoint.

Version 1.64.0

---

CHANGELOG.md
README.md
src/Client.php
src/Endpoints/Cmses.php

Add CMS search & replace endpoint.

Version 1.66.0

---

CHANGELOG.md
README.md
src/Client.php
src/ClusterApi.php
src/Endpoints/RedisInstances.php
src/Enums/NodeGroup.php
src/Models/RedisInstance.php

Version 1.68.0
